# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female'), (b'Other', b'Other')], default=b'Male', max_length=6),
        ),
    ]
