# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0002_auto_20160812_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='group_joined',
        ),
        migrations.AddField(
            model_name='group',
            name='group_admin',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='readbooks.Reader'),
            preserve_default=False,
        ),
    ]
