# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0003_auto_20160803_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
