# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0003_auto_20160815_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_heading',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
