# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0004_topic_topic_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
    ]
