# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import readbooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0005_auto_20160803_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(upload_to=readbooks.models.book_upload_directory),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(to='readbooks.Publisher'),
        ),
    ]
