# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0006_auto_20160804_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='readbooks.Author'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishers',
        ),
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='readbooks.Publisher'),
            preserve_default=False,
        ),
    ]
