# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0007_auto_20160804_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishers',
            new_name='publisher',
        ),
    ]
