# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0008_auto_20160804_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
