# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readbooks', '0009_remove_author_date_of_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critic',
            name='email',
        ),
        migrations.RemoveField(
            model_name='critic',
            name='password',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='password',
        ),
        migrations.AddField(
            model_name='critic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='critic',
            name='user_type',
            field=models.CharField(default=b'Critic', max_length=6),
        ),
        migrations.AddField(
            model_name='reader',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reader',
            name='user_type',
            field=models.CharField(default=b'Reader', max_length=6),
        ),
    ]
