# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0011_auto_20160809_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='recommender',
        ),
        migrations.RemoveField(
            model_name='booksreadbyusers',
            name='books',
        ),
        migrations.RemoveField(
            model_name='booksreadbyusers',
            name='readers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='readerscurrentlyread',
            options={},
        ),
        migrations.RemoveField(
            model_name='readerscurrentlyread',
            name='book_status_message',
        ),
        migrations.RemoveField(
            model_name='readerscurrentlyread',
            name='message_time',
        ),
        migrations.AddField(
            model_name='reader',
            name='bio',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookRecommendation',
        ),
        migrations.DeleteModel(
            name='BooksReadByUsers',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
